### ISSUE TITLE
Change default player

### ISSUE THREAD

**Issue by joaojotta** [jonian/acestream-launcher#27]
That's pretty much it: is it possible to change the default player for acestream-launcher when opening a `acestream://` from the browser?

**Comment by jonian** [comment]
There is no config for this but you can copy the `.desktop` file from [here](https://github.com/jonian/acestream-launcher/blob/master/acestream-launcher.desktop) in `~/.local/share/applications` and modify the `Exec=` and `TryExec=` to set the player.

**Comment by jonian** [comment]
Configuration file support added. Check the readme.

**Comment by pauloonlineprcs** [comment]
> Isso é muito bonito: é possível alterar o player padrão para o lançador de acestream ao abrir um a `acestream://`partir do navegador?

Please, help me! I have this problem.

**Comment by jonian** [comment]
@pauloonlineprcs Use the configuration file as described in the readme:

https://github.com/jonian/acestream-launcher#configuration

**Comment by pauloonlineprcs** [comment]
I do not understand programming at all. I read these instructions
several times but I did not understand anything. I want that when
clicking on a Torrent Magnetic Link my Windows 10 open Windows Media
CLASSIC and it plays the streaming of the Magic Player extension but
the extension opens the Windows Media PLAYER. In the Default
Application Settings on my Windows 10, Windows Media Player is
associated with some formats. Which one do I change so that the Magic
Player extension opens Windows Media CLASSIC to open instead of
Windows Media PLAYER?


Em sáb, 22 de jun de 2019 às 04:34, Jonian Guveli <notifications@github.com>
escreveu:

**Comment by pauloonlineprcs** [comment]
> @pauloonlineprcs Use the configuration file as described in the readme:
> 
> https://github.com/jonian/acestream-launcher#configuration

I do not understand programming at all. I read these instructions several times but I did not understand anything. I want that when clicking on a Torrent Magnetic Link my Windows 10 open Windows Media CLASSIC and it plays the streaming of the Magic Player extension but the extension opens the Windows Media PLAYER. In the Default Application Settings on my Windows 10, Windows Media Player is associated with some formats. Which one do I change so that the Magic Player extension opens Windows Media CLASSIC to open instead of Windows Media PLAYER?

**Comment by jonian** [comment]
@pauloonlineprcs Sorry, I do not use Windows and I don't know how to help you.
